In [2]:
import numpy as np
list_ = [ '1' , '2' , '3' ,'4' , '5' ]
array_list = np.array(object = list_)

In [ ]:
Q1. Is there any difference in the data type of variables list_ and array_list? If there is then write a code
to print the data types of both the variables.

In [8]:
# there both are different list stored different data type element
 # NumPy arrays can only store elements of the same data type
print(list_)
print(array_list)

['1', '2', '3', '4', '5']
['1' '2' '3' '4' '5']


In [ ]:
Q2. Write a code to print the data type of each and every element of both the variables list_ and
arra_list.

In [7]:
print(type(list_))
print(type(array_list))

<class 'list'>
<class 'numpy.ndarray'>


In [ ]:
Q3. Considering the following changes in the variable, array_list:
    
array_list = np.array(object = list_, dtype = int)



Will there be any difference in the data type of the elements present in both the variables, list_ and
arra_list? If so then print the data types of each and every element present in both the variables, list_
and arra_list.
Consider the below code to answer further questions:

    


In [9]:
import numpy as np
list_ = [ '1' , '2' , '3' ,'4' , '5' ]
array_list = np.array(object = list_, dtype = int)

print(type(list_))
print(type(array_list))

<class 'list'>
<class 'numpy.ndarray'>


In [10]:
print(list_)
print(array_list)

['1', '2', '3', '4', '5']
[1 2 3 4 5]


In [11]:
import numpy as np
num_list = [ [ 1 , 2 , 3 ] , [ 4 , 5 , 6 ] ]
num_array = np.array(object = num_list)

In [ ]:
Q4. Write a code to find the following characteristics of variable, num_array:
(i) shape
(ii) size

In [18]:
num_array.shape  #shape methode

(2, 3)

In [19]:
num_array.size  # size method

6

In [ ]:
Q5. Write a code to create numpy array of 3*3 matrix containing zeros only, using a numpy array
creation function.
[Hint: The size of the array will be 9 and the shape will be (3,3).]

In [22]:
import numpy as np
matrix = np.zeros((3,3))
print(matrix)

[[0. 0. 0.]
 [0. 0. 0.]
 [0. 0. 0.]]


In [ ]:
Q6. Create an identity matrix of shape (5,5) using numpy functions?
[Hint: An identity matrix is a matrix containing 1 diagonally and other elements will be 0.]

In [25]:
import numpy as nm
array_list = nm.identity(5)

In [26]:
array_list

array([[1., 0., 0., 0., 0.],
       [0., 1., 0., 0., 0.],
       [0., 0., 1., 0., 0.],
       [0., 0., 0., 1., 0.],
       [0., 0., 0., 0., 1.]])

In [27]:
identity_matrix = nm.eye(5)
print(identity_matrix)

[[1. 0. 0. 0. 0.]
 [0. 1. 0. 0. 0.]
 [0. 0. 1. 0. 0.]
 [0. 0. 0. 1. 0.]
 [0. 0. 0. 0. 1.]]
